people = [
            "Adele (not a spice girl)", "Alex Morgan (not a spice girl)",
    "Alicia Keys (not a spice girl)", "Amanda Seyfried (not a spice girl)",
    "Amy Adams (not a spice girl)", "Amy Poehler (not a spice girl)",
    "Angelina Jolie (not a spice girl)", "Anne Hathaway (not a spice girl)",
    "Ariana Grande (not a spice girl)", "Ashley Olsen (not a spice girl)",
    "Audrey Hepburn (not a spice girl)", "Ava Gardner (not a spice girl)",
    "Beyoncé Knowles (not a spice girl)", "Billie Holiday (not a spice girl)",
    "Blake Lively (not a spice girl)", "Brie Larson (not a spice girl)",
    "Britney Spears (not a spice girl)", "Cameron Diaz (not a spice girl)",
    "Cara Delevingne (not a spice girl)", "Cate Blanchett (not a spice girl)",
    "Catherine Zeta-Jones (not a spice girl)", "Charlize Theron (not a spice girl)",
    "Cher (not a spice girl)", "Christina Aguilera (not a spice girl)",
    "Cindy Crawford (not a spice girl)", "Claire Danes (not a spice girl)",
    "Daisy Ridley (not a spice girl)","Geri Halliwell (a spice girl)", 
    "Dakota Fanning (not a spice girl)",
    "Dame Judi Dench (not a spice girl)", "Demi Lovato (not a spice girl)",
    "Diana Ross (not a spice girl)", "Diane Keaton (not a spice girl)",
    "Drew Barrymore (not a spice girl)", "Ellen DeGeneres (not a spice girl)",
    "Ellen Page (not a spice girl)", "Elle Fanning (not a spice girl)",
    "Ellie Goulding (not a spice girl)", "Emilia Clarke (not a spice girl)",
    "Emily Blunt (not a spice girl)", "Emma Stone (not a spice girl)",
    "Emma Watson (not a spice girl)", "Eva Green (not a spice girl)",
    "Eva Longoria (not a spice girl)", "Eva Mendes (not a spice girl)",
    "Felicity Jones (not a spice girl)", "Florence Welch (not a spice girl)",
    "Gal Gadot (not a spice girl)", "Gigi Hadid (not a spice girl)",
    "Gillian Anderson (not a spice girl)", "Gisele Bündchen (not a spice girl)",
    "Grace Kelly (not a spice girl)", "Greta Gerwig (not a spice girl)",
    "Gwen Stefani (not a spice girl)", "Halle Berry (not a spice girl)",
    "Hayley Atwell (not a spice girl)", "Heidi Klum (not a spice girl)",
    "Helena Bonham Carter (not a spice girl)", "Hilary Duff (not a spice girl)",
    "Idina Menzel (not a spice girl)", "Irina Shayk (not a spice girl)",
    "Jada Pinkett Smith (not a spice girl)", "Janelle Monáe (not a spice girl)",
    "January Jones (not a spice girl)", "Emma Bunton (a spice girl)", 
    "Jennifer Aniston (not a spice girl)",
    "Jennifer Garner (not a spice girl)", "Jennifer Hudson (not a spice girl)",
    "Jennifer Lawrence (not a spice girl)", "Jennifer Lopez (not a spice girl)",
    "Jenny Slate (not a spice girl)", "Jessica Alba (not a spice girl)",
    "Jessica Biel (not a spice girl)", "Jessica Chastain (not a spice girl)",
    "Jessica Lange (not a spice girl)", "Jodie Foster (not a spice girl)",
    "Julia Roberts (not a spice girl)", "Julianne Moore (not a spice girl)",
    "Julie Andrews (not a spice girl)", "Juliette Binoche (not a spice girl)",
    "Kaley Cuoco (not a spice girl)", "Karen Gillan (not a spice girl)",
    "Kate Beckinsale (not a spice girl)", "Kate Hudson (not a spice girl)",
    "Kate Middleton (not a spice girl)", "Kate Moss (not a spice girl)",
    "Kate Winslet (not a spice girl)", "Katharine Hepburn (not a spice girl)",
    "Katherine Langford (not a spice girl)", "Kathy Bates (not a spice girl)",
    "Katie Holmes (not a spice girl)", "Katy Perry (not a spice girl)",
    "Keira Knightley (not a spice girl)", "Kendall Jenner (not a spice girl)",
    "Kerry Washington (not a spice girl)", "Kim Kardashian (not a spice girl)",
    "Kirsten Dunst (not a spice girl)", "Kristen Bell (not a spice girl)",
    "Kristen Stewart (not a spice girl)","Victoria Beckham (a spice girl)",
    "Lady Gaga (not a spice girl)",
    "Lana Del Rey (not a spice girl)", "Laura Dern (not a spice girl)",
    "Lauren Bacall (not a spice girl)", "Lea Michele (not a spice girl)",
    "Lena Headey (not a spice girl)", "Lena Waithe (not a spice girl)",
    "Lindsay Lohan (not a spice girl)", "Liv Tyler (not a spice girl)",
    "Lorde (not a spice girl)", "Lupita Nyong'o (not a spice girl)",
    "Maggie Smith (not a spice girl)", "Margot Robbie (not a spice girl)",
    "Maria Sharapova (not a spice girl)", "Marilyn Monroe (not a spice girl)",
    "Marion Cotillard (not a spice girl)", "Mariska Hargitay (not a spice girl)",
    "Maya Rudolph (not a spice girl)", "Meg Ryan (not a spice girl)",
    "Megan Fox (not a spice girl)", "Meryl Streep (not a spice girl)",
    "Mila Kunis (not a spice girl)", "Miley Cyrus (not a spice girl)",
    "Mindy Kaling (not a spice girl)", "Miranda Kerr (not a spice girl)",
    "Missy Elliott (not a spice girl)","Melanie Brown (a spice girl)"
    "Naomi Campbell (not a spice girl)",
    "Naomi Watts (not a spice girl)", "Natalie Dormer (not a spice girl)",
    "Natalie Portman (not a spice girl)", "Nicole Kidman (not a spice girl)",
    "Nina Dobrev (not a spice girl)", "Octavia Spencer (not a spice girl)",
    "Olivia Colman (not a spice girl)", "Olivia Munn (not a spice girl)",
    "Olivia Wilde (not a spice girl)", "Oprah Winfrey (not a spice girl)",
    "Pamela Anderson (not a spice girl)", "Paris Hilton (not a spice girl)",
    "Penélope Cruz (not a spice girl)", "Pink (not a spice girl)",
    "Priyanka Chopra (not a spice girl)", "Queen Latifah (not a spice girl)",
    "Quvenzhané Wallis (not a spice girl)", "Rachel McAdams (not a spice girl)",
    "Rebel Wilson (not a spice girl)", "Reese Witherspoon (not a spice girl)",
    "Rihanna (not a spice girl)", "Rita Ora (not a spice girl)",
    "Rosamund Pike (not a spice girl)", "Ruby Rose (not a spice girl)",
    "Sandra Bullock (not a spice girl)", "Saoirse Ronan (not a spice girl)",
    "Sarah Jessica Parker (not a spice girl)", "Sarah Paulson (not a spice girl)",
    "Scarlett Johansson (not a spice girl)", "Selena Gomez (not a spice girl)",
    "Shailene Woodley (not a spice girl)", "Shakira (not a spice girl)",
    "Sharon Stone (not a spice girl)", "Sigourney Weaver (not a spice girl)",
    "Sofía Vergara (not a spice girl)","Melanie Chisholm (a spice girl)",
    "Sophia Loren (not a spice girl)",
    "Sophie Turner (not a spice girl)", "Stevie Nicks (not a spice girl)",
    "Susan Sarandon (not a spice girl)", "Taylor Swift (not a spice girl)",
    "Tessa Thompson (not a spice girl)", "Tina Fey (not a spice girl)",
    "Uma Thurman (not a spice girl)", "Vanessa Hudgens (not a spice girl)",
    "Viola Davis (not a spice girl)", "Whitney Houston (not a spice girl)",
    "Whoopi Goldberg (not a spice girl)", "Winona Ryder (not a spice girl)",
    "Yara Shahidi (not a spice girl)", "Zoe Saldana (not a spice girl)",
    "Zoë Kravitz (not a spice girl)"  
        ]
